// Generated by https://quicktype.io

export interface Place {
  id: string;
  name: string;
  location: Location;
}

export interface Location {
  address: string;
  crossStreet: string;
  lat: number;
  lng: number;
  labeledLatLngs: LabeledLatLng[];
  distance: number;
  postalCode: string;
  cc: string;
  city: string;
  state: string;
  country: string;
  formattedAddress: string[];
}

export interface LabeledLatLng {
  label: string;
  lat: number;
  lng: number;
}
